services:
  node-app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: mercat_app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=mercat_mariadb
      - USER=root
      - PASSWORD=root123
      - DB=dwec2ev
      - TOKEN_SECRET=antonio
    depends_on:
      - mariadb
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: mercat_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: dwec2ev
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mercat_phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mercat_mariadb
      - PMA_PORT=3306
    depends_on:
      - mariadb
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge